### ... başka bir sembol için veri almak ister misiniz?

In [7]:
from pybroker import ExecContext, Strategy, YFinance, highest

def exec_fn(ctx: ExecContext):
    if ctx.symbol == 'NVDA':
        other_bar_data = ctx.foreign('AMD')
        other_highest = ctx.indicator('high_10d', 'AMD')
        
strategy = Strategy(YFinance(), start_date='1/1/2022', end_date='1/1/2023')
strategy.add_execution(
   exec_fn, ['NVDA', 'AMD'], indicators=highest('high_10d', 'close', period=10))
result = strategy.backtest()

Backtesting: 2022-01-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  2 of 2 completed
Loaded bar data: 0:00:00

Computing indicators...

  0% (0 of 2) |                          | Elapsed Time: 0:00:00 ETA:  --:--:--
 50% (1 of 2) |#############             | Elapsed Time: 0:00:01 ETA:   0:00:01
100% (2 of 2) |##########################| Elapsed Time: 0:00:01 Time:  0:00:01

Test split: 2022-01-03 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 251) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (251 of 251) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:02

### ... limit fiyat belirlensin mi?

In [8]:
from pybroker import ExecContext, Strategy, YFinance

def buy_fn(ctx: ExecContext):
    if not ctx.long_pos():
        ctx.buy_shares = 100
        ctx.buy_limit_price = ctx.close[-1] * 0.99
        ctx.hold_bars = 10
        
strategy = Strategy(YFinance(), start_date='3/1/2022', end_date='1/1/2023')
strategy.add_execution(buy_fn, 'XU100.IS')
result = strategy.backtest()
result.orders.head(10)

Backtesting: 2022-03-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:00

Test split: 2022-03-01 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 211) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (211 of 211) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

    type    symbol       date  shares  limit_price  fill_price  fees
id
1    buy  XU100.IS 2022-04-22      39      2531.23     2513.25   0.0
2   sell  XU100.IS 2022-05-11      39          NaN     2464.85   0.0
3    buy  XU100.IS 2022-05-12      40      2429.36     2395.95   0.0
4   sell  XU100.IS 2022-05-27      40          NaN     2452.10   0.0
5    buy  XU100.IS 2022-06-08      38      2621.72     2608.75   0.0
6   sell  XU100.IS 2022-06-22      38          NaN     2569.50   0.0
7    buy  XU100.IS 2022-06-27      39      2528.56     2515.85   0.0
8   sell  XU100.IS 2022-07-13      39          NaN     2414.45   0.0
9    buy  XU100.IS 2022-09-13      26      3612.71     3571.10   0.0
10  sell  XU100.IS 2022-09-27      26          NaN     3287.80   0.0

### ... dolum fiyatı belirlensin mi?

In [9]:
from pybroker import ExecContext, PriceType, Strategy, YFinance

def exec_fn(ctx: ExecContext):
    if ctx.long_pos():
        ctx.buy_shares = 100
        ctx.buy_fill_price = PriceType.AVERAGE
    else:
        ctx.sell_shares = 100
        ctx.sell_fill_price = PriceType.CLOSE
        
strategy = Strategy(YFinance(), start_date='3/1/2022', end_date='1/1/2023')
strategy.add_execution(buy_fn, 'XU100.IS')
result = strategy.backtest()
result.orders.head(10)

Backtesting: 2022-03-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:00

Test split: 2022-03-01 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 211) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (211 of 211) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

    type    symbol       date  shares  limit_price  fill_price  fees
id
1    buy  XU100.IS 2022-04-22      39      2531.23     2513.25   0.0
2   sell  XU100.IS 2022-05-11      39          NaN     2464.85   0.0
3    buy  XU100.IS 2022-05-12      40      2429.36     2395.95   0.0
4   sell  XU100.IS 2022-05-27      40          NaN     2452.10   0.0
5    buy  XU100.IS 2022-06-08      38      2621.72     2608.75   0.0
6   sell  XU100.IS 2022-06-22      38          NaN     2569.50   0.0
7    buy  XU100.IS 2022-06-27      39      2528.56     2515.85   0.0
8   sell  XU100.IS 2022-07-13      39          NaN     2414.45   0.0
9    buy  XU100.IS 2022-09-13      26      3612.71     3571.10   0.0
10  sell  XU100.IS 2022-09-27      26          NaN     3287.80   0.0

### ... mevcut pozisyonları aldınız mı?

In [10]:
from pybroker import ExecContext, Strategy, YFinance

def exec_fn(ctx: ExecContext):
    # Tüm pozisyonları alın.
    all_positions = tuple(ctx.positions())
    # Tüm uzun pozisyonları alın.
    long_positions = tuple(ctx.long_positions())
    # Tüm kısa pozisyonları alın.
    short_positions = tuple(ctx.short_positions())
    # Mevcut ctx.symbol için uzun pozisyon alın.
    long_position = ctx.long_pos()
    # Bir sembol için kısa pozisyon alın.
    short_position = ctx.short_pos('XU30.IS')
        
strategy = Strategy(YFinance(), start_date='3/1/2022', end_date='1/1/2023')
strategy.add_execution(exec_fn, ['XU100.IS', 'XU30.IS'])
result = strategy.backtest()

Backtesting: 2022-03-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  2 of 2 completed

1 Failed download:
- XU30.IS: No timezone found, symbol may be delisted
Loaded bar data: 0:00:00

Test split: 2022-03-01 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 211) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (211 of 211) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

[Daha fazla bilgi için Konum sınıfına bakın.](https://www.pybroker.com/en/latest/reference/pybroker.portfolio.html#pybroker.portfolio.Position)

### ... özel sütun verileri kullanılsın mı?

In [11]:
import pybroker
from pybroker import ExecContext, Strategy, YFinance

yf = YFinance()
df = yf.query('XU100.IS', start_date='1/1/2022', end_date='1/1/2023')
df['buy_signal'] = 1

def buy_fn(ctx: ExecContext):
    if not ctx.long_pos() and ctx.buy_signal[-1] == 1:
        ctx.buy_shares = 100
        ctx.hold_bars = 1
        
pybroker.register_columns('buy_signal')
strategy = Strategy(df, start_date='3/1/2022', end_date='1/1/2023')
strategy.add_execution(buy_fn, 'XU100.IS')
result = strategy.backtest()
result.orders.head(10)

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:00

Backtesting: 2022-03-01 00:00:00 to 2023-01-01 00:00:00

Test split: 2022-03-01 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 211) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (211 of 211) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

    type    symbol       date  shares  limit_price  fill_price  fees
id
1    buy  XU100.IS 2022-03-02      50          NaN     1980.70   0.0
2   sell  XU100.IS 2022-03-03      50          NaN     2028.15   0.0
3    buy  XU100.IS 2022-03-04      50          NaN     2007.45   0.0
4   sell  XU100.IS 2022-03-07      50          NaN     1987.70   0.0
5    buy  XU100.IS 2022-03-08      50          NaN     2009.05   0.0
6   sell  XU100.IS 2022-03-09      50          NaN     2043.25   0.0
7    buy  XU100.IS 2022-03-10      50          NaN     2047.65   0.0
8   sell  XU100.IS 2022-03-11      50          NaN     2055.30   0.0
9    buy  XU100.IS 2022-03-14      49          NaN     2079.40   0.0
10  sell  XU100.IS 2022-03-15      49          NaN     2089.45   0.0

### ... birden fazla çubuk ileriden sipariş mi verilsin?

In [12]:
from pybroker import ExecContext, Strategy, StrategyConfig, YFinance

def buy_fn(ctx: ExecContext):
    if not tuple(ctx.pending_orders()) and not ctx.long_pos():
        ctx.buy_shares = 100
        ctx.hold_bars = 1

config = StrategyConfig(buy_delay=5)
strategy = Strategy(YFinance(), start_date='3/1/2022', end_date='1/1/2023', config=config)
strategy.add_execution(buy_fn, 'XU100.IS')
result = strategy.backtest()
result.orders.head(10)

Backtesting: 2022-03-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:02

Test split: 2022-03-01 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 211) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (211 of 211) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:02

    type    symbol       date  shares  limit_price  fill_price  fees
id
1    buy  XU100.IS 2022-03-08      49          NaN     2009.05   0.0
2   sell  XU100.IS 2022-03-09      49          NaN     2043.25   0.0
3    buy  XU100.IS 2022-03-16      48          NaN     2088.35   0.0
4   sell  XU100.IS 2022-03-17      48          NaN     2120.15   0.0
5    buy  XU100.IS 2022-03-24      47          NaN     2185.35   0.0
6   sell  XU100.IS 2022-03-25      47          NaN     2184.40   0.0
7    buy  XU100.IS 2022-04-01      45          NaN     2242.75   0.0
8   sell  XU100.IS 2022-04-04      45          NaN     2287.95   0.0
9    buy  XU100.IS 2022-04-11      43          NaN     2425.55   0.0
10  sell  XU100.IS 2022-04-12      43          NaN     2448.10   0.0

### ... bekleyen siparişler iptal edilsin mi?

In [13]:
from pybroker import ExecContext, Strategy, StrategyConfig, YFinance

def buy_fn(ctx: ExecContext):
    pending = tuple(ctx.pending_orders())
    if not pending and not ctx.long_pos():
        ctx.buy_shares = 100
        ctx.hold_bars = 1
    if pending and ctx.close[-1] < 430:
        ctx.cancel_all_pending_orders(ctx.symbol)

config = StrategyConfig(buy_delay=5)
strategy = Strategy(YFinance(), start_date='3/1/2022', end_date='1/1/2023', config=config)
strategy.add_execution(buy_fn, 'XU100.IS')
result = strategy.backtest()
result.orders.head(10)

Backtesting: 2022-03-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:01

Test split: 2022-03-01 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 211) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (211 of 211) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:01

    type    symbol       date  shares  limit_price  fill_price  fees
id
1    buy  XU100.IS 2022-03-08      49          NaN     2009.05   0.0
2   sell  XU100.IS 2022-03-09      49          NaN     2043.25   0.0
3    buy  XU100.IS 2022-03-16      48          NaN     2088.35   0.0
4   sell  XU100.IS 2022-03-17      48          NaN     2120.15   0.0
5    buy  XU100.IS 2022-03-24      47          NaN     2185.35   0.0
6   sell  XU100.IS 2022-03-25      47          NaN     2184.40   0.0
7    buy  XU100.IS 2022-04-01      45          NaN     2242.75   0.0
8   sell  XU100.IS 2022-04-04      45          NaN     2287.95   0.0
9    buy  XU100.IS 2022-04-11      43          NaN     2425.55   0.0
10  sell  XU100.IS 2022-04-12      43          NaN     2448.10   0.0


### ... çubuklar arasında veriler kalıcı olsun mu?

In [14]:
from pybroker import ExecContext, Strategy, YFinance

def buy_fn(ctx: ExecContext):
    if not ctx.long_pos():
        ctx.buy_shares = 100
        ctx.hold_bars = 1
        count = ctx.session.get('entry_count', 0)
        ctx.session['entry_count'] = count + 1

strategy = Strategy(YFinance(), start_date='1/1/2022', end_date='1/1/2023')
strategy.add_execution(buy_fn, 'XU100.IS')
result = strategy.backtest()

Backtesting: 2022-01-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:00

Test split: 2022-01-03 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 252) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (252 of 252) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

### ... bir pozisyondan çıkılsın mı?

In [15]:
from pybroker import ExecContext, Strategy, YFinance

def buy_fn(ctx: ExecContext):
    pos = ctx.long_pos()
    if not pos:
        ctx.buy_shares = 100
    elif pos.bars > 30:
        ctx.sell_all_shares()

strategy = Strategy(YFinance(), start_date='1/1/2022', end_date='1/1/2023')
strategy.add_execution(buy_fn, 'XU100.IS')
result = strategy.backtest()
result.trades

Backtesting: 2022-01-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:00

Test split: 2022-01-03 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 252) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (252 of 252) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

,type,symbol,entry_date,exit_date,entry,exit,shares,pnl,return_pct,agg_pnl,bars,pnl_per_bar,stop
id,,,,,,,,,,,,,
1,long,XU100.IS,2022-01-04,2022-02-17,1951.65,2034.55,51,4227.90,4.25,4227.90,32,132.12,None
2,long,XU100.IS,2022-02-18,2022-04-05,2018.45,2323.60,51,15562.65,15.12,19790.55,32,486.33,None
3,long,XU100.IS,2022-04-06,2022-05-26,2328.25,2438.45,51,5620.20,4.73,25410.75,32,175.63,None
4,long,XU100.IS,2022-05-27,2022-07-14,2452.10,2398.10,51,-2754.00,-2.20,22656.75,32,-86.06,None
5,long,XU100.IS,2022-07-18,2022-09-01,2426.60,3154.25,50,36382.50,29.99,59039.25,32,1136.95,None
6,long,XU100.IS,2022-09-02,2022-10-18,3194.35,3866.35,49,32928.00,21.04,91967.25,32,1029.00,None
7,long,XU100.IS,2022-10-19,2022-12-02,3880.70,4983.65,49,54044.55,28.42,146011.80,32,1688.89,None

### ... aynı anda birden fazla sembol işlensin mi?

In [16]:
from pybroker import ExecContext, Strategy, YFinance

def long_short_fn(ctxs: dict[str, ExecContext]):
    nvda_ctx = ctxs['DOAS.IS']
    amd_ctx = ctxs['FROTO.IS']
    if nvda_ctx.long_pos() or amd_ctx.short_pos():
        return
    if nvda_ctx.bars >= 2 and nvda_ctx.close[-1] < nvda_ctx.low[-2]:
        nvda_ctx.buy_shares = 100
        nvda_ctx.hold_bars = 3
        amd_ctx.sell_shares = 100
        amd_ctx.hold_bars = 3

strategy = Strategy(YFinance(), start_date='1/1/2022', end_date='1/1/2023')
strategy.add_execution(None, ['DOAS.IS', 'FROTO.IS'])
strategy.set_after_exec(long_short_fn)
result = strategy.backtest()
result.trades

Backtesting: 2022-01-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  2 of 2 completed
Loaded bar data: 0:00:00

Test split: 2022-01-03 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 252) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (252 of 252) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

,type,symbol,entry_date,exit_date,entry,exit,shares,pnl,return_pct,agg_pnl,bars,pnl_per_bar,stop
id,,,,,,,,,,,,,
1,long,DOAS.IS,2022-01-07,2022-01-12,43.55,44.18,100,63.0,1.45,63.0,3,21.00,bar
2,short,FROTO.IS,2022-01-07,2022-01-12,257.80,255.70,100,210.0,0.82,273.0,3,70.00,bar
3,long,DOAS.IS,2022-01-19,2022-01-24,48.27,49.13,100,86.0,1.78,359.0,3,28.67,bar
4,short,FROTO.IS,2022-01-19,2022-01-24,260.55,247.30,100,1325.0,5.36,1684.0,3,441.67,bar
5,long,DOAS.IS,2022-01-25,2022-01-28,47.27,48.53,100,126.0,2.67,1810.0,3,42.00,bar
6,short,FROTO.IS,2022-01-25,2022-01-28,241.75,250.15,100,-840.0,-3.36,970.0,3,-280.00,bar
7,long,DOAS.IS,2022-02-04,2022-02-09,47.50,48.78,100,128.0,2.69,1098.0,3,42.67,bar
8,short,FROTO.IS,2022-02-04,2022-02-09,238.60,248.90,100,-1030.0,-4.14,68.0,3,-343.33,bar
9,long,DOAS.IS,2022-02-15,2022-02-18,47.08,48.96,100,188.0,3.99,256.0,3,62.67,bar
10,short,FROTO.IS,2022-02-15,2022-02-18,251.15,262.85,100,-1170.0,-4.45,-914.0,3,-390.00,bar
11,long,DOAS.IS,2022-02-23,2022-02-28,48.80,46.34,100,-246.0,-5.04,-1160.0,3,-82.00,bar
12,short,FROTO.IS,2022-02-23,2022-02-28,267.25,265.45,100,180.0,0.68,-980.0,3,60.00,bar
13,long,DOAS.IS,2022-03-21,2022-03-24,58.25,60.48,100,223.0,3.83,-757.0,3,74.33,bar
14,short,FROTO.IS,2022-03-21,2022-03-24,296.15,302.55,100,-640.0,-2.12,-1397.0,3,-213.33,bar
15,long,DOAS.IS,2022-03-30,2022-04-04,60.02,63.27,100,325.0,5.41,-1072.0,3,108.33,bar
16,short,FROTO.IS,2022-03-30,2022-04-04,299.90,306.55,100,-665.0,-2.17,-1737.0,3,-221.67,bar
17,long,DOAS.IS,2022-04-11,2022-04-14,63.50,61.80,100,-170.0,-2.68,-1907.0,3,-56.67,bar
18,short,FROTO.IS,2022-04-11,2022-04-14,306.30,304.00,100,230.0,0.76,-1677.0,3,76.67,bar
19,long,DOAS.IS,2022-04-22,2022-04-27,69.95,68.47,100,-148.0,-2.12,-1825.0,3,-49.33,bar
20,short,FROTO.IS,2022-04-22,2022-04-27,306.30,301.30,100,500.0,1.66,-1325.0,3,166.67,bar
21,long,DOAS.IS,2022-05-13,2022-05-18,66.25,64.12,100,-213.0,-3.22,-1538.0,3,-71.00,bar
22,short,FROTO.IS,2022-05-13,2022-05-18,284.95,280.25,100,470.0,1.68,-1068.0,3,156.67,bar
23,long,DOAS.IS,2022-05-20,2022-05-25,63.40,65.80,100,240.0,3.79,-828.0,3,80.00,bar
24,short,FROTO.IS,2022-05-20,2022-05-25,276.10,282.70,100,-660.0,-2.33,-1488.0,3,-220.00,bar
25,long,DOAS.IS,2022-06-09,2022-06-14,69.53,69.35,100,-18.0,-0.26,-1506.0,3,-6.00,bar
26,short,FROTO.IS,2022-06-09,2022-06-14,298.55,288.50,100,1005.0,3.48,-501.0,3,335.00,bar
27,long,DOAS.IS,2022-06-28,2022-07-01,79.53,75.75,100,-378.0,-4.75,-879.0,3,-126.00,bar
28,short,FROTO.IS,2022-06-28,2022-07-01,294.60,272.70,100,2190.0,8.03,1311.0,3,730.00,bar
29,long,DOAS.IS,2022-07-06,2022-07-13,72.65,79.28,100,663.0,9.13,1974.0,3,221.00,bar
30,short,FROTO.IS,2022-07-06,2022-07-13,260.35,268.15,100,-780.0,-2.91,1194.0,3,-260.00,bar
31,long,DOAS.IS,2022-07-20,2022-07-25,84.88,82.90,100,-198.0,-2.33,996.0,3,-66.00,bar
32,short,FROTO.IS,2022-07-20,2022-07-25,261.20,272.55,100,-1135.0,-4.16,-139.0,3,-378.33,bar
33,long,DOAS.IS,2022-07-26,2022-07-29,81.62,84.08,100,246.0,3.01,107.0,3,82.00,bar
34,short,FROTO.IS,2022-07-26,2022-07-29,280.90,296.20,100,-1530.0,-5.17,-1423.0,3,-510.00,bar
35,long,DOAS.IS,2022-08-04,2022-08-09,85.08,82.75,100,-233.0,-2.74,-1656.0,3,-77.67,bar
36,short,FROTO.IS,2022-08-04,2022-08-09,313.05,323.40,100,-1035.0,-3.20,-2691.0,3,-345.00,bar
37,long,DOAS.IS,2022-08-29,2022-09-02,98.50,99.60,100,110.0,1.12,-2581.0,3,36.67,bar
38,short,FROTO.IS,2022-08-29,2022-09-02,338.80,332.45,100,635.0,1.91,-1946.0,3,211.67,bar
39,long,DOAS.IS,2022-09-07,2022-09-12,98.92,103.70,100,478.0,4.83,-1468.0,3,159.33,bar
40,short,FROTO.IS,2022-09-07,2022-09-12,335.60,356.10,100,-2050.0,-5.76,-3518.0,3,-683.33,bar
41,long,DOAS.IS,2022-09-14,2022-09-19,97.50,104.70,100,720.0,7.38,-2798.0,3,240.00,bar
42,short,FROTO.IS,2022-09-14,2022-09-19,345.45,346.35,100,-90.0,-0.26,-2888.0,3,-30.00,bar
43,long,DOAS.IS,2022-09-27,2022-09-30,102.15,94.65,100,-750.0,-7.34,-3638.0,3,-250.00,bar
44,short,FROTO.IS,2022-09-27,2022-09-30,338.35,327.05,100,1130.0,3.46,-2508.0,3,376.67,bar
45,long,DOAS.IS,2022-10-13,2022-10-18,101.47,106.65,100,518.0,5.10,-1990.0,3,172.67,bar
46,short,FROTO.IS,2022-10-13,2022-10-18,339.55,362.50,100,-2295.0,-6.33,-4285.0,3,-765.00,bar
47,long,DOAS.IS,2022-11-04,2022-11-09,122.00,122.05,100,5.0,0.04,-4280.0,3,1.67,bar
48,short,FROTO.IS,2022-11-04,2022-11-09,358.15,364.85,100,-670.0,-1.84,-4950.0,3,-223.33,bar
49,long,DOAS.IS,2022-11-17,2022-11-22,138.70,151.55,100,1285.0,9.26,-3665.0,3,428.33,bar
50,short,FROTO.IS,2022-11-17,2022-11-22,408.80,443.05,100,-3425.0,-7.73,-7090.0,3,-1141.67,bar
51,long,DOAS.IS,2022-12-08,2022-12-13,148.10,160.80,100,1270.0,8.58,-5820.0,3,423.33,bar
52,short,FROTO.IS,2022-12-08,2022-12-13,414.40,443.10,100,-2870.0,-6.48,-8690.0,3,-956.67,bar

### ... Sharpe Oranı yıllıklaştırılsın mı?

[bars_per_year](https://www.pybroker.com/en/latest/reference/pybroker.config.html#pybroker.config.StrategyConfig.bars_per_year) yapılandırma seçeneğini ayarlayın. Örneğin, günlük getirilerin yıllıklaştırılması için "252" değerinin ayarlanması kullanılacaktır.

In [17]:
from pybroker import ExecContext, Strategy, StrategyConfig, YFinance

def buy_fn(ctx: ExecContext):
    if ctx.long_pos() or ctx.bars < 2:
        return
    if ctx.close[-1] < ctx.high[-2]:
        ctx.buy_shares = 100
        ctx.hold_bars = 1

config = StrategyConfig(bars_per_year=252)
strategy = Strategy(YFinance(), start_date='1/1/2022', end_date='1/1/2023', config=config)
strategy.add_execution(buy_fn, 'XU100.IS')
result = strategy.backtest()
result.metrics.sharpe

Backtesting: 2022-01-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:00

Test split: 2022-01-03 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 252) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (252 of 252) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:01

3.2194846468837675

### ... açığa satış için kullanılan limit marjı?

Varsayılan olarak PyBroker, açığa satış için kullanılabilecek marj miktarını sınırlamaz. Ancak kullanılabilecek marjin miktarını manuel olarak sınırlayabilirsiniz:

In [18]:
import pybroker
from pybroker import ExecContext
from decimal import Decimal

def short_fn(ctx: ExecContext):
    margin_requirement = Decimal('0.25')
    max_margin = ctx.total_equity / margin_requirement - ctx.total_equity
    if not ctx.short_pos():
        available_margin = max_margin - ctx.total_margin
        ctx.sell_shares = ctx.calc_target_shares(0.5, cash=available_margin)
        ctx.hold_bars = 1
        
strategy = Strategy(YFinance(), start_date='1/1/2022', end_date='1/1/2023')
strategy.add_execution(short_fn, ['DOAS.IS', 'FROTO.IS'])
result = strategy.backtest()
result.portfolio.head(10)

Backtesting: 2022-01-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  2 of 2 completed
Loaded bar data: 0:00:00

Test split: 2022-01-03 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 252) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
 63% (161 of 252) |##############        | Elapsed Time: 0:00:00 ETA:  00:00:00
100% (252 of 252) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:01

,cash,equity,margin,market_value,pnl,unrealized_pnl,fees
date,,,,,,,
2022-01-03,100000.00,100000.00,0.00,100000.00,0.00,0.00,0.0
2022-01-04,100000.00,100000.00,304395.96,98703.36,0.00,-1296.64,0.0
2022-01-05,97777.06,97777.06,0.00,97777.06,-2222.94,0.00,0.0
2022-01-06,97777.06,97777.06,287247.11,100604.27,-2222.94,2827.21,0.0
2022-01-07,102039.98,102039.98,0.00,102039.98,2039.98,0.00,0.0
2022-01-10,102039.98,102039.98,302745.37,106459.16,2039.98,4419.18,0.0
2022-01-11,105379.89,105379.89,0.00,105379.89,5379.89,0.00,0.0
2022-01-12,105379.89,105379.89,314498.62,108365.53,5379.89,2985.64,0.0
2022-01-13,92785.87,92785.87,0.00,92785.87,-7214.13,0.00,0.0
2022-01-14,92785.87,92785.87,290713.00,85028.56,-7214.13,-7757.31,0.0

### ... global bir parametre alıp ayarlamak ister misiniz?

In [19]:
import pybroker

# Parametreyi ayarlayın.
pybroker.param('lookback', 100)

# Parametreyi al.
pybroker.param('lookback')

100

### ... rastgele kayma uygulansın mı?

Bir [RandomSlippageModel](https://www.pybroker.com/en/latest/reference/pybroker.slippage.html#pybroker.slippage.RandomSlippageModel) ayarlayın:

In [20]:
from pybroker import ExecContext, RandomSlippageModel, Strategy, YFinance

def buy_fn(ctx: ExecContext):
    if not ctx.long_pos():
        ctx.buy_shares = 100
        ctx.hold_bars = 1

slippage = RandomSlippageModel(min_pct=1.0, max_pct=5.0) # Slippage of 1-5%
strategy = Strategy(YFinance(), start_date='3/1/2022', end_date='1/1/2023')
strategy.set_slippage_model(slippage)
strategy.add_execution(buy_fn, 'XU100.IS')
result = strategy.backtest()
result.orders.head(10)

Backtesting: 2022-03-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:00

Test split: 2022-03-01 00:00:00 to 2022-12-30 00:00:00

  0% (0 of 211) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
100% (211 of 211) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

    type    symbol       date  shares  limit_price  fill_price  fees
id
1    buy  XU100.IS 2022-03-02      50          NaN     1980.70   0.0
2   sell  XU100.IS 2022-03-03      50          NaN     2028.15   0.0
3    buy  XU100.IS 2022-03-04      50          NaN     2007.45   0.0
4   sell  XU100.IS 2022-03-07      50          NaN     1987.70   0.0
5    buy  XU100.IS 2022-03-08      50          NaN     2009.05   0.0
6   sell  XU100.IS 2022-03-09      50          NaN     2043.25   0.0
7    buy  XU100.IS 2022-03-10      50          NaN     2047.65   0.0
8   sell  XU100.IS 2022-03-11      50          NaN     2055.30   0.0
9    buy  XU100.IS 2022-03-14      49          NaN     2079.40   0.0
10  sell  XU100.IS 2022-03-15      49          NaN     2089.45   0.0